volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      device: /home/mingkang/data/mariadb
      o: bind
  WP:
    driver: local
    driver_opts:
      type: none
      device: /home/mingkang/data/wordpress
      o: bind

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - DB:/var/lib/mysql
    networks:
      - mingkangnet
    env_file:
      - ./.env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - WP:/var/www/html
    networks:
      - mingkangnet
    env_file:
      - ./.env
    restart: always
    tty: true
    depends_on:
      - mariadb
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - WP:/var/www/html
    networks:
      - mingkangnet
    restart: always
    tty: true
    depends_on:
      - wordpress
networks:
  mingkangnet:
    driver: bridge
